apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: simulator
spec:
  baseRefs:
    - name: maas-demo-simulator-template
  model:
    uri: hf://facebook/opt-125m
    name: facebook/opt-125m
  replicas: 1
  router:
    route: {}
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
  template:
    containers:
      - name: main
        env:
          - name: SIM_MODEL
            value: "simulator/premium-model"
