apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: simulator
spec:
  baseRefs:
    - name: maas-demo-simulator-template
  model:
    uri: hf://sshleifer/tiny-gpt2 # ~2MB test model; simulator ignores weights
    name: facebook/opt-125m
  replicas: 1
  router:
    route: {}
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
